# Generated by Django 4.2.27 on 2026-01-26 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Theme name (e.g., 'Dark Blue', 'Light Mode')", max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one theme can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_type', models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Background Image')], default='gradient', max_length=20)),
                ('background_color_1', models.CharField(default='#0f172a', help_text='Primary background color (hex)', max_length=7)),
                ('background_color_2', models.CharField(default='#581c87', help_text='Secondary color for gradients (hex)', max_length=7)),
                ('background_color_3', models.CharField(default='#0f172a', help_text='Tertiary color for gradients (hex)', max_length=7)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='theme_backgrounds/')),
                ('background_opacity', models.IntegerField(default=100, help_text='Background opacity (0-100)')),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#a855f7', help_text='Secondary accent color (hex)', max_length=7)),
                ('accent_color', models.CharField(default='#ec4899', help_text='Accent/highlight color (hex)', max_length=7)),
                ('text_primary', models.CharField(default='#ffffff', help_text='Primary text color (hex)', max_length=7)),
                ('text_secondary', models.CharField(default='#d1d5db', help_text='Secondary text color (hex)', max_length=7)),
                ('text_muted', models.CharField(default='#9ca3af', help_text='Muted text color (hex)', max_length=7)),
                ('navbar_background', models.CharField(default='#1e293b', help_text='Navbar background color (hex)', max_length=7)),
                ('navbar_text', models.CharField(default='#ffffff', help_text='Navbar text color (hex)', max_length=7)),
                ('navbar_opacity', models.IntegerField(default=90, help_text='Navbar opacity (0-100)')),
                ('navbar_blur', models.BooleanField(default=True, help_text='Enable glassmorphism blur effect')),
                ('font_family', models.CharField(choices=[('inter', 'Inter (Modern Sans-serif)'), ('outfit', 'Outfit (Display Font)'), ('roboto', 'Roboto (Clean & Professional)'), ('poppins', 'Poppins (Geometric Sans)'), ('montserrat', 'Montserrat (Urban & Stylish)'), ('lato', 'Lato (Humanist Sans)'), ('opensans', 'Open Sans (Friendly & Open)'), ('raleway', 'Raleway (Elegant Thin)')], default='inter', max_length=50)),
                ('font_size_base', models.IntegerField(default=16, help_text='Base font size in pixels (14-20)')),
                ('font_size_heading', models.IntegerField(default=36, help_text='Heading font size in pixels (24-48)')),
                ('line_height', models.FloatField(default=1.6, help_text='Line height multiplier (1.2-2.0)')),
                ('card_background_opacity', models.IntegerField(default=12, help_text='Card background opacity (0-100)')),
                ('card_border_opacity', models.IntegerField(default=25, help_text='Card border opacity (0-100)')),
                ('card_blur_amount', models.IntegerField(default=16, help_text='Blur amount in pixels (0-32)')),
                ('card_shadow', models.BooleanField(default=True, help_text='Enable card shadows')),
                ('button_style', models.CharField(choices=[('gradient', 'Gradient'), ('solid', 'Solid Color'), ('outline', 'Outline')], default='gradient', max_length=20)),
                ('button_rounded', models.IntegerField(default=12, help_text='Button border radius in pixels (0-24)')),
                ('button_shadow', models.BooleanField(default=True, help_text='Enable button shadows')),
                ('animation_speed', models.CharField(choices=[('slow', 'Slow (1.5s)'), ('normal', 'Normal (1s)'), ('fast', 'Fast (0.5s)'), ('none', 'No Animations')], default='normal', max_length=20)),
                ('enable_hover_effects', models.BooleanField(default=True, help_text='Enable hover animations')),
                ('enable_page_transitions', models.BooleanField(default=True, help_text='Enable page transition effects')),
                ('enable_floating_orbs', models.BooleanField(default=True, help_text='Enable floating background orbs')),
                ('orb_opacity', models.IntegerField(default=30, help_text='Orb opacity (0-100)')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS code (advanced users)', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Theme',
                'verbose_name_plural': 'Site Themes',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
