# Generated by Django 5.0.1 on 2026-01-27 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_sitetheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Feature title', max_length=100)),
                ('description', models.TextField(help_text='Feature description')),
                ('icon', models.CharField(choices=[('fa-robot', 'Robot (AI)'), ('fa-chart-line', 'Chart (Analytics)'), ('fa-certificate', 'Certificate'), ('fa-clock', 'Clock'), ('fa-infinity', 'Infinity'), ('fa-mobile-alt', 'Mobile'), ('fa-brain', 'Brain'), ('fa-graduation-cap', 'Graduation Cap'), ('fa-trophy', 'Trophy'), ('fa-star', 'Star'), ('fa-bolt', 'Lightning Bolt'), ('fa-users', 'Users')], default='fa-star', max_length=50)),
                ('icon_gradient', models.CharField(choices=[('from-blue-500 to-purple-600', 'Blue to Purple'), ('from-purple-500 to-pink-600', 'Purple to Pink'), ('from-pink-500 to-red-600', 'Pink to Red'), ('from-blue-500 to-cyan-500', 'Blue to Cyan'), ('from-green-500 to-emerald-600', 'Green to Emerald'), ('from-yellow-500 to-orange-600', 'Yellow to Orange'), ('from-indigo-500 to-blue-600', 'Indigo to Blue'), ('from-red-500 to-pink-600', 'Red to Pink')], default='from-blue-500 to-purple-600', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='MindSpark AI', max_length=100)),
                ('brand_tagline', models.CharField(default='Empowering learners worldwide with AI-powered education.', max_length=200)),
                ('brand_icon', models.CharField(default='fa-brain', help_text='FontAwesome icon class', max_length=50)),
                ('copyright_text', models.CharField(default='MindSpark AI Quiz. All rights reserved.', max_length=200)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='AI-Powered Learning Platform', max_length=100)),
                ('heading_line1', models.CharField(default='Transform Your Learning', max_length=100)),
                ('heading_line2', models.CharField(default='with ', max_length=100)),
                ('heading_highlight', models.CharField(default='AI-Generated Quizzes', max_length=100)),
                ('subheading', models.TextField(default='Experience personalized learning powered by advanced AI. Generate custom quizzes on any topic, track your progress, and achieve your learning goals faster.')),
                ('cta_primary_text', models.CharField(default='Start Learning Free', max_length=50)),
                ('cta_primary_url', models.CharField(default='register', help_text='Django URL name or path', max_length=200)),
                ('cta_secondary_text', models.CharField(default='See How It Works', max_length=50)),
                ('cta_secondary_url', models.CharField(default='#how-it-works', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='SectionHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('features', 'Features Section'), ('testimonials', 'Testimonials Section'), ('how_it_works', 'How It Works Section'), ('cta', 'Call to Action Section')], max_length=20, unique=True)),
                ('title', models.CharField(help_text='Main heading', max_length=200)),
                ('subtitle', models.TextField(help_text='Subheading/description')),
            ],
            options={
                'verbose_name': 'Section Heading',
                'verbose_name_plural': 'Section Headings',
            },
        ),
        migrations.CreateModel(
            name='StatCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., '10K+', '50K+', '95%'", max_length=50)),
                ('subtitle', models.CharField(help_text="e.g., 'Active Learners', 'Quizzes Generated'", max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stat Card',
                'verbose_name_plural': 'Stats Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Person's name", max_length=100)),
                ('role', models.CharField(help_text="e.g., 'Medical Student', 'Software Developer'", max_length=100)),
                ('testimonial', models.TextField(help_text='Their testimonial/review')),
                ('rating', models.IntegerField(default=5, help_text='Star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar_letter', models.CharField(blank=True, help_text='First letter for avatar (auto-filled from name if empty)', max_length=1)),
                ('avatar_gradient', models.CharField(default='from-indigo-500 to-purple-600', help_text='Avatar background gradient (Tailwind classes)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials Section',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('product', 'Product'), ('company', 'Company'), ('support', 'Support'), ('legal', 'Legal')], default='product', max_length=20)),
                ('text', models.CharField(help_text='Link text', max_length=100)),
                ('url', models.CharField(help_text="URL or Django URL name (e.g., '#features' or 'login')", max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('footer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='quiz.footersection')),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['column', 'order'],
            },
        ),
    ]
